#!/bin/bash
#Place in cron.daily (or however often you would like to back it up)
DAY="$(date "+%a")"
world="world"
backupdir="/opt/minecraft/backups"
mountdir="/opt/minecraft/server"

echo "removing files older than a week..."
#Remove files of type .tgz that are older than a week
find "${backupdir}/" -type f -mtime +7 -name '*.tgz' -execdir rm -- '{}' +
echo "backing up world ${world}..."
#Backup the server to a specified directory
tar -zcvf "${backupdir}/${DAY}_${world}.tgz" -C "${mountdir}" "${world}"
#if backup fails...
if [ $? -ne 0 ]; then
  echo "tar operation failed!"
  loopvar=$false
  exit 1
fi
#Exit the loop/script
echo "complete"
exit 0
